"""initial schema

Revision ID: d5f1a89df868
Revises: 
Create Date: 2026-06-12 23:09:16.414347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f1a89df868'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('payer_type', sa.String(), nullable=False),
    sa.Column('denial_profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('npi', sa.String(), nullable=True),
    sa.Column('plan_tier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('synthetic_mrn', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('payer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('dos', sa.String(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('provider_npi', sa.String(), nullable=False),
    sa.Column('clinical_note', sa.Text(), nullable=False),
    sa.Column('dx_hints', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_tenant_id'), 'encounters', ['tenant_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('encounter_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_charge', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_claim_id'), 'audit_events', ['claim_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('claim_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('code_type', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('charge', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_codes_claim_id'), 'claim_codes', ['claim_id'], unique=False)
    op.create_table('denials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('carc_code', sa.String(), nullable=False),
    sa.Column('rarc_code', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('appealable', sa.Boolean(), nullable=False),
    sa.Column('appeal_letter', sa.Text(), nullable=True),
    sa.Column('appeal_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denials_claim_id'), 'denials', ['claim_id'], unique=False)
    op.create_table('eligibility_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('copay', sa.Float(), nullable=False),
    sa.Column('deductible', sa.Float(), nullable=False),
    sa.Column('raw_271', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_checks_claim_id'), 'eligibility_checks', ['claim_id'], unique=False)
    op.create_table('remittances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('allowed_amount', sa.Float(), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=False),
    sa.Column('raw_835', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittances_claim_id'), 'remittances', ['claim_id'], unique=False)
    op.create_table('scrub_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('clean', sa.Boolean(), nullable=False),
    sa.Column('edits', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrub_results_claim_id'), 'scrub_results', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrub_results_claim_id'), table_name='scrub_results')
    op.drop_table('scrub_results')
    op.drop_index(op.f('ix_remittances_claim_id'), table_name='remittances')
    op.drop_table('remittances')
    op.drop_index(op.f('ix_eligibility_checks_claim_id'), table_name='eligibility_checks')
    op.drop_table('eligibility_checks')
    op.drop_index(op.f('ix_denials_claim_id'), table_name='denials')
    op.drop_table('denials')
    op.drop_index(op.f('ix_claim_codes_claim_id'), table_name='claim_codes')
    op.drop_table('claim_codes')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_claim_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_encounters_tenant_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('tenants')
    op.drop_table('payers')
    # ### end Alembic commands ###
